### ISSUE TITLE
File ClassPowSetting.cs missing

### ISSUE THREAD

**Issue by reuniware** [XIROPHT/Xiropht-Connector-All#1]
Hello.

I've tried to compile this DLL in order to import it to Xiropht-Desktop-Wallet (in order to compile this latter) but the ClassPowSetting.cs is missing...

Could you provide it or explain what is needed to do to get it ?

Thanks

**Comment by reuniware** [comment]
Impossible to post a message on the Discord board...

**Comment by XIROPHT** [comment]
Hi,

The development project of the mining PoW process has been cancelled, since the decentralized version is in development.

Please reach the repository of the development of the new technology who will be used in the future: https://github.com/SamSegura/segurachain
